basePath: /
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: Timefill Api
    url: http://www.swagger.io/support
  description: This is a server timefull-api-go
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Timefill API Go
  version: "2.0"
paths: {}
swagger: "2.0"
